name: hydrosmart
description: "A smart water conservation app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.70.0        # Current stable version
  glassmorphism: ^3.0.0   # Updated version (Fixes your error)
  google_fonts: ^6.2.0    # Current stable version
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7
  http: ^1.6.0
  flutter_markdown: ^0.7.7+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.20.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  assets:
    - .env
  uses-material-design: true
